#!/bin/bash
# Check button state and light up led when pressed

set -eu

BUTTON_PIN=${BUTTON_PIN:-0}
LIGHT_PIN=${LIGHT_PIN:-1}
MQTT_PASS=${MQTT_PASS:-changeservice}

# Configure pins
gpio mode $BUTTON_PIN in
gpio mode $LIGHT_PIN out

# Force initial update
last_state=-1

mqtt_notify() {
  echo -n 'mqtt: '
  mosquitto_pub --capath /etc/ssl/certs/ -h matrix.hackeriet.no -p 8883 -t 'hackeriet/space_state' -d -u humladoor -P $MQTT_PASS -r -m $1
}

while true; do
  btn_state=$(gpio read $BUTTON_PIN)

  # Only write to pin when needed
  if [ x$btn_state != x$last_state ]; then
    gpio write $LIGHT_PIN $btn_state
    echo "Button state set to $btn_state"
    last_state=$btn_state

    # Allow for e.g. MQTT network errors to occur without exiting the program
    set +e
    if [ "$btn_state" -eq "1" ]; then
      mqtt_notify OPEN
    else
      mqtt_notify CLOSED
    fi
    set -e
  fi

  sleep 0.1
done
