#!/bin/bash
# Check button state and light up led when pressed

set -eu

BUTTON_PIN=${BUTTON_PIN:-0}
LIGHT_PIN=${LIGHT_PIN:-1}
MQTT_PASS=${MQTT_PASS:-changeservice}

# Configure pins
gpio mode $BUTTON_PIN in
gpio mode $LIGHT_PIN out

# Force initial update
last_state=-1

while true; do
  btn_state=$(gpio read $BUTTON_PIN)

  # Only write to pin when needed
  if [ x$btn_state != x$last_state ]; then
    if [ "$btn_state" -eq "1" ]; then
      mosquitto_pub --capath /etc/ssl/certs/ -h matrix.hackeriet.no -p 8883 -t 'hackeriet/space_state' -m OPEN -d -u humladoor -P $MQTT_PASS
    else
      mosquitto_pub --capath /etc/ssl/certs/ -h matrix.hackeriet.no -p 8883 -t 'hackeriet/space_state' -m CLOSED -d -u humladoor -P $MQTT_PASS
    fi
    gpio write $LIGHT_PIN $btn_state
    echo "Button state set to $btn_state"
    last_state=$btn_state
  fi

  sleep 0.1
done
